/*
 * Image Resize
 *
 * This is a Image Resize server.
 *
 * API version: 1.0.0
 * Contact: fedorenko.tolik@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"

	"github.com/gorilla/mux"
)

// Route ...
type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

// Routes ...
type Routes []Route

// NewRouter ...
func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

// Index is the main router
func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello, to upload image please open /images url")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"ImagesPost",
		"POST",
		"/images",
		ImagesPost,
	},

	Route{
		"ImageFormShow",
		"GET",
		"/images",
		ImageFormShow,
	},

	Route{
		"ImageShow",
		"GET",
		"/images/{size}/{imageId}",
		ImageShow,
	},
}
